import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import MainLayout from '@/containers/mainlayout'
import DeepDiveManager from '@/containers/deepdivemanager'

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='w-full h-full'>
      <body className={`w-full h-full ${lato.className}`}>
        <DeepDiveManager />
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  )
}
